name: LiteBans-TemplateStack
version: '1.0.0'
main: xyz.jackoneill.litebans.templatestack.TemplateStackPlugin
api-version: '1.20'
authors: [ Jack O'Neill ]
website: https://jackoneill.xyz

softdepend:
  - LiteBans

permissions:
  litebans.templatestack:
    description: permission for using the administrative commands of templatestack
    default: op
  litebans.templatestack.punish:
    description: permission for executing punishment command
    default: op
  litebans.templatestack.reload:
    description: permission to reload configuration of templatestack
    default: op
