name: LiteBans-TemplateStack
version: '1.0.0'
main: xyz.jackoneill.litebans.templatestack.TemplateStackPlugin
api-version: '1.20'
authors: [ Jack O'Neill ]
website: https://jackoneill.xyz

softdepend:
  - LiteBans